---
- name: Simple Infrastructure Deployment
  hosts: localhost
  connection: local
  gather_facts: false
  
  vars:
    deploy_components: []
    work_dir: "/tmp/ansible-deployments"
    
    # Git repositories - set these to actual repo URLs
    k3s_repo: "https://github.com/t822940/k3s.git"
    awx_repo: "https://github.com/t822940/awx.git"
    ipam_repo: "https://github.com/t822940/ipam.git"

  tasks:
    - name: Create working directory
      file:
        path: "{{ work_dir }}"
        state: directory
        mode: '0755'

    - name: Clone K3s repository
      git:
        repo: "{{ k3s_repo }}"
        dest: "{{ work_dir }}/k3s_deployment"
        force: yes
      when: "'k3s' in deploy_components and k3s_repo != ''"

    - name: Clone AWX repository
      git:
        repo: "{{ awx_repo }}"
        dest: "{{ work_dir }}/awx_deployment"
        force: yes
      when: "'awx' in deploy_components and awx_repo != ''"

    - name: Clone IPAM repository
      git:
        repo: "{{ ipam_repo }}"
        dest: "{{ work_dir }}/ipam_deployment"
        force: yes
      when: "'ipam' in deploy_components and ipam_repo != ''"

    - name: Check if K3s is already running
      command: /usr/local/bin/k3s kubectl get nodes
      register: k3s_running
      failed_when: false
      when: "'k3s' in deploy_components"

    - name: Deploy K3s
      ansible.builtin.command:
        cmd: ansible-playbook -i inventory k3s.yml
        chdir: "{{ work_dir }}/k3s_deployment"
      when: "'k3s' in deploy_components and k3s_running.rc != 0"

    - name: Fix PostgreSQL data directory permissions
      file:
        path: /opt/awx-postgres-data
        state: directory
        mode: '0777'
        owner: 70
        group: 70
      become: yes
      when: "'awx' in deploy_components"

    - name: Deploy AWX
      ansible.builtin.command:
        cmd: ansible-playbook -i localhost, main.yml
        chdir: "{{ work_dir }}/awx_deployment"
      when: "'awx' in deploy_components"

    - name: Deploy IPAM
      ansible.builtin.command:
        cmd: ansible-playbook playbook.yml
        chdir: "{{ work_dir }}/ipam_deployment"
      when: "'ipam' in deploy_components"

    - name: Display status
      debug:
        msg: "Deployed: {{ deploy_components | join(', ') }}"
